server:
  hostname: "shiny.dide.ic.ac.uk"
  email: "r.fitzjohn@imperial.ac.uk"
  port_http: 80
  port_https: 443
  port_admin: 9000
  # used for the self-signed certificate
  country: UK
  state: London
  organisation: DIDE

vault:
  address: "https://vault.dide.ic.ac.uk:8200"
  root: "/secret/shiny.dide"

apps:
  typochallenge:
    type: github
    spec: mrc-ide/typochallenge@external
    protect:
      paths:
        - emails.db
        - contributions
    secret:
      .redis:
        path: "misc/redis-url"
        field: value
      .googlesheets-oauth:
        path: "misc/googlesheets-oauth"
        field: token
        binary: true
    schedule:
      update_googlesheets:
        frequency: "@hourly"
        command: ./update_googlesheets
        enabled: false
    admin:
      - acori

  eppasmviewer:
    type: github
    spec: mrc-ide/eppasmviewer/inst/shiny/eppasmviewer
    auth:
      type: deploy_key
    groups:
      - dide-internal
    admin:
      - jeff

  polici:
    type: github
    spec: arranhamlet/POLICI
    
  seasonal_hrp2
    type: github
    spec: ojwatson/hrp2malaRia/inst/shiny-seasonality/app
    username: ojwatson
    
  hello:
    type: local
    spec: hello

  test:
    type: local
    spec: test
    groups:
      - dide-internal

groups:
  dide-internal:
    - rich
    - jeff
    - acori
  admin:
    - rich
